language: nix
install: travis_wait nix-shell
script: travis_wait nix-build .

# Deploy PDFs to Github Pages
# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: result
  on:
    branch: master
